### ISSUE TITLE
Which service for clients?

### ISSUE THREAD

**Issue by neverfox** [eliaslevy/docker-zookeeper#1]
Taking the example Kubernetes template in the README, is the idea that clients can now just connect to the one `zookeeper` service, e.g. `zookeeper:2181`, or do they still need to target all cluster members as usual, e.g. `zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181`? To ask in a more concrete way, if one were to use your docker-kafka project alongside this one, which is the appropriate setting for `ZOOKEEPER_SERVERS`? I tried this and Kafka starts fine just pointing at the former, but I'm not certain if that's going to ultimately be problematic under load.

**Comment by eliaslevy** [comment]
You point the clients to the `zookeeper:2181` service.  The client's don't care which Zookeeper instance they talk to.  The instance specific services are there for use by Zookeeper, as each instance needs to connect to all other instances concurrently to form a quorum.

**Comment by neverfox** [comment]
@eliaslevy Thanks!
