### ISSUE TITLE
What happens if a pod dies and is replaced?

### ISSUE THREAD

**Issue by devth** [eliaslevy/docker-zookeeper#2]
Is there any manual intervention required or does the fresh ZK member gracefully catch up / continue work on a new pod? 

I assume it's useful to use a persistent volume mount for `/zookeeper/data` – is that correct?

**Comment by eliaslevy** [comment]
A new member to a ZK ensemble synchronizes it's state with the ensemble.  A ZK member recovering from a failure that has order state, as as by using a persistent volume, will synchronize with the ensemble using the state is has as a base.
